# pii_patterns:
#   aadhar: r'\b\d{4}-\d{4}-\d{4}\b|\b\d{12}\b'
#   pan: r'\b[A-Z]{5}[0-9]{4}[A-Z]\b'
pii_patterns:
  aadhar: true
  pan: true
ocr:
  languages: 'eng+hin'  

redaction:
  color: 'black' 
